### PR TITLE
update SSAStepper to allow multiple events per step

### PR DESCRIPTION
**Pull request by isaacsas**
https://github.com/SciML/DiffEqJump.jl/issues/177

@ChrisRackauckas this is what I was thinking of doing. Do you see a problem with this? (One issue is whether we want to allow saving after each jump, what this PR does, or only save after all the jumps.)

If this sounds reasonable let's see if tests pass.

### CODE REVIEW

**Comment by isaacsas** [comment]
If this seems reasonable I'll add a test too.

**Comment by ChrisRackauckas** [comment]
This is reasonable for SSAIntegrator. We should also have a good strategy that combines well with the ODE/SDE solvers though, but that could come at a later time. In reality, with hybrid, you'd want to never run into this issue if you're doing it right.

**Comment by ChrisRackauckas** [comment]
>with hybrid, you'd want to never run into this issue if you're doing it right.

That comment is going to come back 2 years from now, I just know it.

**Comment by isaacsas** [comment]
This is a fundamental issue is all the SSAs I think, so it will definitely occur in hybrid too for long enough `tspan`s.

**Comment by isaacsas** [comment]
Shoot, I think we've got a catch-22 with this solution. If we don't include the callbacks in the loop then one potentially misses a callback. If you do include them you potentially execute a callback too many times.

**Comment by isaacsas** [comment]
OK, so this just executes all the jumps, which means that callbacks are no longer exact. It is a hack, but gives a fix for now. I'll keep the issue open and next month can work on a more robust solution.

**Pull request merged**
