### PR TITLE
Allow MassActionJumps to use standard parameter vectors

### PR DESCRIPTION
**Pull request by isaacsas**
This should allow a new `MassActionJump` use case
```
p = (1.0, 2.0)

# use 2.0 for the first reaction rate and 1.0 for the second
MassActionJump(reaction_stoich, net_stoich; param_idxs=[2,1], params=p)
```
while preserving compatibility with the old style. Rates are still fixed at construction time, but in this mode they are read from the parameter vector `p` according to the indices in `param_idxs`. This ordering is then saved so that later one can use an updated parameter vector/tuple to update a mass action jump (if it was setup in this way, otherwise the old style will still work just fine).

@ChrisRackauckas if you think this approach makes sense I'll add in a function for remaking in callbacks, which we can subsequently point users too.

### CODE REVIEW

**Comment by isaacsas** [comment]
Once this is done I’ll also update Catalyst and MT to use this as the default.

**Review by ChrisRackauckas — APPROVED** [review]
This is mostly good. I can still see a potential issue with callbacks, but this is infinitely better than before.

**Comment by isaacsas** [comment]
@ChrisRackauckas I wanted to check the approach with you before handling callbacks... I've just put them in now. Basically `remake` and `reset_aggrevated_jumps!` should now both update `MassActionJump`s if they were initialized with parameter indices.

**Comment by isaacsas** [comment]
The only consideration is whether we want to not always update the `MassActioJump` parameters in `reset_aggregated_jumps!` (i.e. maybe we should allow user control over this with a kwarg).

**Pull request merged**
