### PR TITLE
add citations to algorithms

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by isaacsas** [comment]
Are you planning to start working on API documentation across SciML?

**Comment by ChrisRackauckas** [comment]
I'm trying to get it there. It's a massive piece of work though.

**Comment by isaacsas** [comment]
I only ask as @Vilin97 had said he would be happy to work on documenting DiffEqJump, but I suggested he focus on graph/spatial SSAs (his planned summer research) instead. If this is a current push though we could see if he is still interested in this.

**Comment by ChrisRackauckas** [comment]
Focus on methods. Documentation can always come. In fact, the time to do documentation is when we pull up all of the papers for writing our own paper, so if he wants to do this, have him start writing the paper 😄

**Pull request merged**
