### PR TITLE
made spatially varying rx rates

### PR DESCRIPTION
**Pull request by Vilin97**
Now users can pass in the `rx_coefficients` kwarg in the construction of `JumpProblem`. `rx_coefficients[i,j]` is the coefficient of reaction i at site j by which the reaction rate will be multiplied

### CODE REVIEW

**Comment by isaacsas** [comment]
@Vilin97 I'm thinking that maybe it would be best to add an explicit `SpatialMassActionJump`, the idea being users can pass both one `MassActionJump`s and one `SpatialMassActionJump` (each encoding possibly many reactions). This has a nice feature that then reactions without spatially varying rates can be more efficiently represented, but those that need varying rates can use the `SpatialMassActionJump`. By clearly separating the types, and also storing them separately and explicitly, we can handle each individually for type stability. It will require a bit more logic though since we'll have to manually split the sampling like we do for `ConstantRateJump`s and `MassActionJump`s currently.

What do you think?

**Comment by yewalenikhil65** [comment]
Do we have any tutorial planned explaining spatially varying rx rates? I was unable to understand the code

**Comment by yewalenikhil65** [comment]
> We haven't added spatially varying reaction rates yet, so there isn't any tutorial. Once this all gets finalized, hopefully in the next month or two, we'll start on some tutorials. We still need to add something like a `SpatialMassActionJump` as I mentioned above.

hey @isaacsas , @Vilin97  sorry for troubling you guys, but is it possible for you guys to please provide me a short example of how to create such spatially varying rates and supply it to `Discreteproblem()` or jumpproblem   using current version of  DiffEqJump ? I would really appreciate a simple example of `A+B-->C` reaction with spatially varying rates ? I really needed it

**Comment by isaacsas** [comment]
There’s @Vilin97’s PR and any tests he added in it, but otherwise we don’t support this yet. The version I want to include will probably use a different interface to the PR based on a new jump type.

**Comment by Vilin97** [comment]
@yewalenikhil65 , if you don't want to wait for spatially varying reaction rates to come to DiffEqJump, you can clone this PR and work with it locally. To understand how to use this PR, look at lines https://github.com/SciML/DiffEqJump.jl/pull/210/files#diff-8e84d9c326ceee4c90d021bf9162d9d98029f4449c5014afaa107b6d18ee6cf1R55 and https://github.com/SciML/DiffEqJump.jl/pull/210/files#diff-8e84d9c326ceee4c90d021bf9162d9d98029f4449c5014afaa107b6d18ee6cf1R57.
Line 57 shows how to create a JumpProblem with spatially varying reaction rates. You simply pass in a `rx_coefficients` kwarg. Line 55 shows what this kwarg should be: a matrix of dimensions (number of reactions) x (number of nodes).

The matrix `rx_coefficients` scales the reaction rates (you can think of it as being a matrix of ones by default). Say, you have two reactions, and three nodes, and you want the propensities to be 1 everywhere, except the first node, where the first reaction has propensity 2. Then `rx_coefficients` should be [2.0 1.0 1.0; 1.0 1.0 1.0]. Does this make sense?

Again, you can use this PR as a temporary solution for your application. Spatially varying rates will be added later on with (most likely) a different interface.

**Comment by yewalenikhil65** [comment]
> @yewalenikhil65 , if you don't want to wait for spatially varying reaction rates to come to DiffEqJump, you can clone this PR and work with it locally. To understand how to use this PR, look at lines https://github.com/SciML/DiffEqJump.jl/pull/210/files#diff-8e84d9c326ceee4c90d021bf9162d9d98029f4449c5014afaa107b6d18ee6cf1R55 and https://github.com/SciML/DiffEqJump.jl/pull/210/files#diff-8e84d9c326ceee4c90d021bf9162d9d98029f4449c5014afaa107b6d18ee6cf1R57. Line 57 shows how to create a JumpProblem with spatially varying reaction rates. You simply pass in a `rx_coefficients` kwarg. Line 55 shows what this kwarg should be: a matrix of dimensions (number of reactions) x (number of nodes).
> 
> The matrix `rx_coefficients` scales the reaction rates (you can think of it as being a matrix of ones by default). Say, you have two reactions, and three nodes, and you want the propensities to be 1 everywhere, except the first node, where the first reaction has propensity 2. Then `rx_coefficients` should be [2.0 1.0 1.0; 1.0 1.0 1.0]. Does this make sense?
> 
> Again, you can use this PR as a temporary solution for your application. Spatially varying rates will be added later on with (most likely) a different interface.

thanks @Vilin97 , i will take a look at these lines

**Comment by isaacsas** [comment]
@Vilin97 we can close this now right?

**Pull request closed without merging**
