### PR TITLE
Attempt to fix complex states with VariableRateJumps

### PR DESCRIPTION
**Pull request by isaacsas**
@ChrisRackauckas this was an attempt to fix

https://discourse.julialang.org/t/differentialequations-jl-package-variable-rate-jumps-with-complex-variables/80366/2

but tests are now failing (locally) in DiffEqBase with respect to callback conditions now being complex. 

Also, this has pointed out that there is no way in some places to get at the user-specified `rng` in `JumpProblem`, which means that we may have a situation where the rng for constant rate jumps is different than for variable rate jumps...

### CODE REVIEW

**Comment by isaacsas** [comment]
OK, with this change tests seem to pass locally, but I'm not sure if this is a bad approach with regards to expectations in DiffEqBase or such.

**Comment by isaacsas** [comment]
I updated to save the `rng` within the `JumpProblem` and use it consistently for `VariableRateJump`s in DiffEqJump.

**Comment by isaacsas** [comment]
Closes https://github.com/SciML/DiffEqJump.jl/issues/226

**Comment by ChrisRackauckas** [comment]
This looks fine. It looks like JumpProblem's remake needs to be updated for the extended jump problem definition as well.

**Comment by rveltz** [comment]
what do you mean by extended problem?

**Comment by ChrisRackauckas** [comment]
the pseudo values used for the rootfinding to get events

**Comment by isaacsas** [comment]
> what do you mean by extended problem?

@rveltz for systems using `VariableRateJump`s the solution vector `u` is augmented into a struct that also stores the sampled exponential random variates for finding event times (as Chris mentioned). See https://github.com/SciML/DiffEqJump.jl/blob/master/src/extended_jump_array.jl

**Pull request merged**
